### ISSUE TITLE
Webpack/rollup

### ISSUE THREAD

**Issue by antony** [moinism/botui#10]
Using an IIFE is great for using this library directly in the web browser, but sadly this makes the library difficult to use in webpack/rollup (I can't actually get it to work).

What would be great is the ability to use botui as part of my existing application:

```javascript
import BotUI from 'botui'
const botui = new BotUI('xyz')
```

You could then use your existing gulp tasks to publish the commonjs module (http://know.cujojs.com/tutorials/modules/authoring-cjs-modules) as an IIFE (as it currently is)

In its current state, it's difficult to integrate cleanly into other projects which might want to use it.

**Comment by moinism** [comment]
Hey @antony!

Its working fine with webpack too. I just tried and have published [an example here](https://github.com/moinism/botui-examples/tree/master/hello-world-webpack).

The tricky part is its dependency of `Vue`. When adding `Vue` via npm, use `vue.min.js` or it may produce errors.
