### ISSUE TITLE
Label of the confirm button for the Text Action   

### ISSUE THREAD

**Issue by semmel** [moinism/botui#14]
Browsing the source, docu and the examples I could not find an option to change the label of the confirm button from "Go". It seems to be fixed in the source.

Would it make sense to add these configuration properties
```javascript
button: {
    icon: 'some-awesome-icon',
    text: 'Send'
}
// or
button_icon:  'some-awesome-icon',
text: 'Send'
```
to `botui.action.text` ?

**Comment by moinism** [comment]
Yeah, it is fixed right now @semmel.

I think it would make sense to add these properties in `object` form. The HTML would changes accordingly though.

**Comment by semmel** [comment]
Ok then I will attempt to create a pull request for adding that functionality
