### ISSUE TITLE
Write example as async function

### ISSUE THREAD

**Issue by pietrasiak** [moinism/botui#5]
I think bot code looks _better_ ® when written as async function.

eg. main example would look like

```
var botui = new BotUI('botui-app'); // give it the id of container

async function conversation() {
  await botui.message.bot({
    // show first message
    delay: 200,
    content: 'hello',
  });
  await botui.message.bot({
    // second one
    delay: 1000, // wait 1 sec.
    content: 'how are you?',
  });
  const res = await botui.action.button({
    // let user do something
    delay: 1000,
    action: [
      { text: 'Good', value: 'good' },
      { text: 'Really Good', value: 'really_good' },
    ],
  });
  await botui.message.bot({
    delay: 1000,
    content: 'You are feeling ' + res.text + '!',
  });
}
```

**Comment by semmel** [comment]
Yes, using async/await came to my mind too. 
However with *BotUI Actions* I find it misleading:
Why block the "render" function `conversation()` as long as the action is pending? It's just an event handler for the action buttons (something every JS programmer should be familiar with) but expressed as promise success callback.
A better structure for your program would be:
```javascript
function onUserFeeling(res) {
  botui.message.bot({
    delay: 1000,
    content: 'You are feeling ' + res.text + '!'
  });
}
// ...
botui.action.button({ // let user do something
    delay: 1000,
    action: [
      { text: 'Good', value: 'good' },
      { text: 'Really Good', value: 'really_good' },
    ]
}).then(onUserFeeling);
```
What is your take on that?

**Comment by moinism** [comment]
It does look better @pietrasiak but I'd have to agree with @semmel here, it's just a callback and blocking doesn't seem right. I think it might even confuse those who are new to `async`/`await`.

But I'm going to add it to the [docs](https://github.com/moinism/botui-docs) in guide section.
