### ISSUE TITLE
Markup / URL / IMG in bot not working

### ISSUE THREAD

**Issue by pk075** [moinism/botui#7]
Hey there,

i am not able to use URL or IMG in the chatbot. Maybe you can help me out here?

```
return botui.message.add({
  delay: 1000,
  loading: true,
  content:'Some companies i recently worked for:'
}).then(function (){
  return botui.message.add({
    delay: 1000,
    loading: true,
    content:'- [Shore](www.shore.com)^'
  });
});
```

**Comment by moinism** [comment]
@pk075 this might be due to `Vue`. Its been noted that newer versions of `Vue` are causing problem with `BotUI markup`.

Please use v2.0.5 of vue if possible, that's the tested/compatible version for BotUI.

**Comment by pk075** [comment]
Working awesome thanks

**Comment by tneben** [comment]
Just a comment, maybe of interest for your project:

Issue persists. Code in "examples" folder won't display images because it is set to use vue _latest_.
I get images displayed up until https://npmcdn.com/vue@**2.0.7**/dist/vue.js
Cheers
