### ISSUE TITLE
Extra information in actions

### ISSUE THREAD

**Issue by guillemaldeguer** [moinism/botui#8]
Hi! Thank you so much for this awesome package.

I want to add some extra information in action structure, but it seems doesn't work.

```javascript
botui.action.button({
   delay: 500,
   action: [
      {
         text: 'Button 1',
         value: 1,
         extra: 'Something'
      }, {
         text: 'Button 2',
         value: 2,
         extra: 'Something'
      }, {
         text: 'Button 3',
         value: 3,
         extra: 'Something'
      }
   ]
});
```

Is there any way to do it?

Thank you!

**Comment by moinism** [comment]
Hey, you are welcome.

Sadly no, there is no way to add anything else to buttons. You can only add icons. 
Like `icon: check` or any other available in font awesome.
