### ISSUE TITLE
Question: what's the best way to branch/repeat a path of conversation?

### ISSUE THREAD

**Issue by TravelingTechGuy** [moinism/botui#9]
I like the idea and implementation. Good job!

My question is: what's the best way to approach a repeating scenario? Say I ask you for something in step 1, ask for another detail in step 2, deliver a result in step 3, and now want to get back to step 1. Recursion can work I assume, with me calling the function again in the last step. But isn't there a better way?

Similarly, do you have any recommendation about branches? the promise chain is one directional. What if I need something more tree like? Will I put every branch of the tree in a separate function and call it in the last step?

I believe some documentation around these scenarios would be beneficial (but I'll be satisfied with an answer :)).

**Comment by moinism** [comment]
For both repeating scenarios and branches, `function`s are the way to go for now.
In next versions we may add an option to define a function to be called after an `action` or a `message`.

I'll try to add examples in guide.
